name: Publish All Client Packages

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to publish (e.g., 0.0.1-alpha27)"
        required: true
        type: string

jobs:
  publish-npm:
    name: Publish NPM Package
    uses: ./.github/workflows/publish-npm.yml
    secrets: inherit

  publish-pypi:
    name: Publish PyPI Package
    needs: publish-npm # Publish PyPI after NPM succeeds
    uses: ./.github/workflows/publish-pypi.yml
    secrets: inherit
