name: Publish to NPM

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (patch, minor, major, or specific version like 1.2.3)'
        required: true
        default: 'patch'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Install dependencies
        run: |
          cd clients/js
          npm ci
          
      - name: Build package
        run: |
          cd clients/js
          npm run build
          
      - name: Run tests
        run: |
          cd clients/js
          npm test
          
      - name: Bump version (if workflow_dispatch)
        if: github.event_name == 'workflow_dispatch'
        run: |
          cd clients/js
          npm version ${{ github.event.inputs.version }} --no-git-tag-version
          
      - name: Publish to NPM
        run: |
          cd clients/js
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: Create git tag (if workflow_dispatch)
        if: github.event_name == 'workflow_dispatch'
        run: |
          cd clients/js
          VERSION=$(node -p "require('./package.json').version")
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add package.json
          git commit -m "Bump version to v$VERSION"
          git tag "v$VERSION"
          git push origin main --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
