name: Publish to NPM

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version tag from private repo (e.g., v1.2.3)"
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: |
          cd clients/js
          SKIP_HOOK_DOWNLOAD=true npm ci

      - name: Build package
        run: |
          cd clients/js
          npm run build

      - name: Run tests
        run: |
          cd clients/js
          npm test

      - name: Update package version
        run: |
          cd clients/js
          # Extract version from tag (remove 'v' prefix)
          VERSION="${{ github.event.inputs.version }}"
          VERSION=${VERSION#v}
          npm version $VERSION --no-git-tag-version

      - name: Publish to NPM
        run: |
          cd clients/js
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
