name: Publish PyPI Package

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # Linux builds (both architectures)
          - os: ubuntu-latest
            archs: [x86_64, aarch64]
          # macOS builds (both architectures)
          - os: macos-latest
            archs: [x86_64, arm64]
          # Windows
          - os: windows-latest
            archs: AMD64

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.0.1
        env:
          CIBW_ARCHS: ${{ matrix.archs }}
        with:
          package-dir: clients/python

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Build sdist
        run: |
          python -m pip install --upgrade pip build
          python -m build --sdist
        working-directory: ./clients/python

      - name: Upload sdist
        uses: actions/upload-artifact@v4
        with:
          name: cibw-sdist
          path: clients/python/dist/*.tar.gz

  pypi-publish:
    name: Publish to PyPI
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: cibw-*
          path: dist
          merge-multiple: true

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
